### ISSUE TITLE
Bilingual connected mode, editing is not possible.

### ISSUE THREAD

**Issue by hakan-x** [brotkrueml/codehighlight#14]
You create a Code Snippet content in the standard language (e.g. German) in the backend, then you want to translate this content into the English language with 'strict translation' it works. But if you now want to edit this content in backend the following error message will be displayed, (1/1) Error Call to a member function isCustomState() on null. It is not possible to edit the backend layout, in the frontend it is displayed with the ‘copy' and ‘translate' hint and I can't delete this hint. How can I solve this problem?
![Error_isCustomState](https://user-images.githubusercontent.com/58939697/70905696-d09b0600-2004-11ea-986a-f0677959d711.jpg)

**Comment by brotkrueml** [comment]
Do you use the latest TYPO3 version (9.5.11) and codehighlight version (2.0.0)? In free or connected translation mode? I would then try to reproduce this behaviour.

**Comment by hakan-x** [comment]
T3 Version 9.5.11
Code Highlight Version 2.0.0
Connected translation mode

**Comment by brotkrueml** [comment]
@hakan-x Thank you for the bug report. An updated version 2.0.1 is now available.
