### ISSUE TITLE
Editor is not working since TYPO3 11.5.18

### ISSUE THREAD

**Issue by PKuhlmay** [brotkrueml/codehighlight#37]
### Current behavior

The bodytext is not shown with TYPO3 11.5.18. With 11.5.17 it worked.

### Steps to reproduce

install TYPO3 11.5.18 and EXT:codehighlight. Try it out and then switch to TYPO3 11.5.17.

### Environment

- Codehighlight version(s): 2.7.0
- TYPO3 version(s): 11.5.18
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by brotkrueml** [comment]
Can confirm with codehighlight 2.12.0. Will have a look into it.

**Comment by brotkrueml** [comment]
Strange, the columnOverrides are not available anymore:
![image](https://user-images.githubusercontent.com/2566282/201483536-a577989d-fb22-4abc-8cd2-f1049813bfe7.png)

**Comment by brotkrueml** [comment]
Okay, seems that

    $GLOBALS['TCA']['tt_content']['types'] += $tempTypes;

does not work anymore. Assigned it directly. Will provide a patch.

**Comment by brotkrueml** [comment]
Thanks for reporting, Philipp :-)

**Comment by brotkrueml** [comment]
Release 2.12.1 is out: https://extensions.typo3.org/extension/codehighlight 🎉
